version: '3.8'

services:
  app:
    image: "node:16-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"

  mysql:
    image: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      DB_ROOT_HOST: "%"
      DB_ROOT_PASS: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}